# Generated by Django 2.0.2 on 2018-03-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'news article'},
        ),
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together={('slug', 'startup')},
        ),
    ]
